version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        image: nginx
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        image: mysql
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql:mysql
        ports:
          - 8081:80
        environment:
          MYSQL_USERNAME: "${DB_USERNAME}"
          MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
          PMA_HOST: mysql
        volumes:
          - ./php-make/upload.ini:/usr/local/etc/php/php.ini
        networks: 
            - laravel
    
     # queue
    queue:
        image: bitnami/laravel
        restart: unless-stopped
        #command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    
    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge