version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php7.4-fpm/Dockerfile    
    container_name: php-library-example    
    command: bash -c "php artisan serve"
    env_file:
      - docker/docker-compose-env/application.env    
    